export enum ProductCategory {
  ELECTRODOMESTICOS = 'ELECTRODOMESTICOS',
  OFICINA = 'OFICINA',
  ACCESORIOS = 'ACCESORIOS',
  ROPA = 'ROPA',
  CALZADO = 'CALZADO',
  TECNOLOGIA = 'TECNOLOGIA',
  JUGUETES = 'JUGUETES',
  DEPORTES = 'DEPORTES',
  SALUD = 'SALUD',
  LIBROS = 'LIBROS',
  AUTOMOTRIZ = 'AUTOMOTRIZ',
  MASCOTAS = 'MASCOTAS',
}
